### ISSUE TITLE
Getting a 404 when trying to publish package from monorepo

### ISSUE THREAD

**Issue by mathix420** [morlay/bunpublish#4]
Package name: `@plsr/nuxt-layer-base`
- `plsr` is an org 
- I used this command `bunx @morlay/bunpublish` in the root of the monorepo
- [Source code](https://github.com/pulsar-inc/nuxt-layers) (it's a bit of a mess currently 😅)

![image](https://github.com/morlay/bunpublish/assets/37625778/e414dc79-2e60-4063-b3b9-440deac570fb)

**Comment by migueldamota** [comment]
I am getting the same error for my monorepo +1

**Comment by migueldamota** [comment]
I managed to solve this. I updated my `bunfig.toml` to not use

```toml
[install.scopes]
scope = { ... }
```

instead use

```toml
[install]
registry = { url = "https://registry.npmjs.org", token = "$NPM_TOKEN" }
```

This works now perfectly fine for me 👍
